name: Cloudflared Quick Tunnel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # اختیاری: هر ۵ ساعت یکبار restart میشه

jobs:
  tunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # ۶ ساعت، حداکثر زمان مجاز گیت‌هاب

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run mhrv-tunnel-node with cloudflared
      uses: docker://ghcr.io/therealaleph/mhrv-tunnel-node:latest
      env:
        TUNNEL_AUTH_KEY: ${{ secrets.TUNNEL_AUTH_KEY }}
        TUNNEL_MODE: full
        TUNNEL_SERVICE: cloudflared
    ```
